version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "centos*"
    default_assignees:
      - "haxorof"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
          dependency_name: "ansible"
      - match:
          update_type: "all"
    default_assignees:
      - "haxorof"
