name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, centos7, ubuntu, main]
        version: [v2.8, v2.9, v2.10, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          if [[ "$MATRIX_OS" == 'main' ]]; then
              # Instead of using symbolic links
              cp Dockerfile.alpine Dockerfile.main > /dev/null 2>&1
              echo "::set-output name=tag::$MATRIX_VERSION"
          else
              echo "::set-output name=tag::${MATRIX_VERSION}-${MATRIX_OS}"
          fi
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        env:
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_VERSION: ${{ matrix.version }}

      # Since sudo is used this will complain and suggest gosu but that
      # needs to be tested if gosu can replace sudo for Ansible use-cases.
      # - name: Lint Dockerfile
      #   uses: docker://replicated/dockerfilelint:latest
      #   with:
      #     args: Dockerfile.${{ matrix.os }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.prep.outputs.tag }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
          build-args: |
            ansible_version=${{ matrix.version }}
            docker_version=20.10.2
            gosu_version=1.12
          tags: haxorof/ansible:${{ steps.prep.outputs.tag }}
          context: .
          file: ./Dockerfile.${{ matrix.os }}
          push: ${{ endsWith(github.ref, '/master') }}

  update_docker_hub_description:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: haxorof/ansible
