name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, centos7, centos8]
        version: [v2.8, v2.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/ansible
          tag_with_sha: false
          tags: ${{ matrix.version }}-${{ matrix.os }}
          dockerfile: ${{ matrix.version }}/Dockerfile.${{ matrix.os }}

  build_push_version_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine]
        version: [v2.8, v2.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/ansible
          tag_with_sha: false
          tags: ${{ matrix.version }}
          dockerfile: ${{ matrix.version }}/Dockerfile.${{ matrix.os }}

  build_push_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/ansible
          tag_with_sha: false
          tags: latest
          dockerfile: v2.9/Dockerfile.alpine
