name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, centos7, centos8]
        version: [v2.8, v2.9, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/ansible
          tag_with_sha: false
          build_args: ansible_version=${{ matrix.version }},docker_version=19.03.8
          tags: ${{ matrix.version }}-${{ matrix.os }}
          dockerfile: Dockerfile.${{ matrix.os }}
          push: ${{ endsWith(github.ref, '/master') }}

  build_push_version_latest:
    needs: build_push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine]
        version: [v2.8, v2.9, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/ansible
          tag_with_sha: false
          build_args: ansible_version=${{ matrix.version }},docker_version=19.03.8
          tags: ${{ matrix.version }}
          dockerfile: Dockerfile.${{ matrix.os }}
          push: ${{ endsWith(github.ref, '/master') }}
