name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * 0'

env:
  IMAGE_NAME: haxorof/ansible

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
      LATEST_OS: alpine
      LATEST_VERSION: v3
      DOCKER_CLI_VERSION: "20.10.6"
      GOSU_VERSION: "1.12"
    strategy:
      matrix:
        os: [almalinux8, alpine, centos8, ubuntu]
        version: [v2.9, v2.10, v3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          cp requirements/requirements-${MATRIX_VERSION}.txt requirements/requirements.txt
          TAGS="${IMAGE_NAME}:${MATRIX_VERSION}-${MATRIX_OS}"
          if [[ "$MATRIX_OS" == "$LATEST_OS" ]]; then
            TAGS="${TAGS},${IMAGE_NAME}:$MATRIX_VERSION"
            if [[ "$MATRIX_VERSION" == "$LATEST_VERSION" ]]; then
              TAGS="${TAGS},${IMAGE_NAME}:latest"
            fi
          elif [[ "$MATRIX_VERSION" == "$LATEST_VERSION" ]]; then
            TAGS="${TAGS},${IMAGE_NAME}:latest-${MATRIX_OS},${IMAGE_NAME}:latest-${MATRIX_OS}"
          fi
          echo "::set-output name=tags::${TAGS}"
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        env:
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_VERSION: ${{ matrix.version }}

      # Since sudo is used this will complain and suggest gosu but that
      # needs to be tested if gosu can replace sudo for Ansible use-cases.
      # - name: Lint Dockerfile
      #   uses: docker://replicated/dockerfilelint:latest
      #   with:
      #     args: Dockerfile.${{ matrix.os }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ endsWith(github.ref, '/master') }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
          build-args: |
            docker_version=${{ env.DOCKER_CLI_VERSION }}
            gosu_version=${{ env.GOSU_VERSION }}
          tags: ${{ steps.prep.outputs.tags }}
          context: .
          file: ./Dockerfile.${{ matrix.os }}
          push: ${{ endsWith(github.ref, '/master') }}

  update_docker_hub_description:
    needs: build_push
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.ref, '/master') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
